export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const CLOSE_SEARCH_RESULT = 'CLOSE_SEARCH_RESULT';
export const DISABLE_SEARCH_INPUT = 'DISABLE_SEARCH_INPUT';

export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';
